baseURL = "http://example.org/"
languageCode = "en-us"
title = "Resume"
theme = "strange-case"

[params]
	colorScheme = "scheme-gulfracing"
	DateFormat = "2 Jan 2006"
	description = "A Hugo Theme built with Bootstrap"
	sidebarDescription = "A Hugo Theme built with Bootstrap"
	sidebarFreeText = ""